server:
  servlet:
    context-path: /browser/
proxy:
  hide-navbar: true
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  container-wait-time: 100000
  authentication: none
  port: 2525
  docker:
    url: http://localhost:2375
    port-range-start: 20000
    port-range-max: 20020
  specs:
  - id: vizER
    display-name: vizER
    container-cmd: ["R", "-e shiny::runApp('/root/vizER')"]
    container-image: vizer
    container-volumes: [ "/home_2/gsit/vizER_data:/root/vizER/vizER_data" ]
  - id: introverse
    display-name: IntroVerse
    container-cmd: ["R", "-e", "shiny::runApp('/root/introverse', host='0.0.0.0', port=3838)"]
    container-image: soniaruiz/introverse:latest
logging:
  file:
    shinyproxy.log

  