server:
  servlet:
    context-path: /browser/
proxy:
  hide-navbar: true
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  container-wait-time: 100000
  authentication: none
  favicon-path: https://github.com/SoniaRuiz/introverse/blob/main/introverse/www/introverse.ico
  port: 2525
  docker:
    url: http://localhost:2375
    port-range-start: 20000
    port-range-max: 30020
  specs:
  - id: introverse
    display-name: IntroVerse
    container-cmd: ["R", "-e", "shiny::runApp('/root/introverse', host='0.0.0.0', port=3838)"]
    container-image: soniaruiz/introverse:latest
    access-groups: [shiny]
logging:
  file:
    shinyproxy.log
